before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  main: ./lukki.go
  ldflags:
    - -X github.com/Lepovirta/lukki/internal/buildinfo.Version={{.Version}}
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - "386"
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
