version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Setup
          command: go mod download
      - run:
          name: Test
          command: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run:
          name: Build
          command: go build
      - codecov/upload:
          file: coverage.txt

  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Release to GitHub
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
